// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEE4DgsAAal4GqxFaxUNCtibUEBhxVvWA',
    appId: '1:224817571256:web:7ace6bad670181f43f9b4d',
    messagingSenderId: '224817571256',
    projectId: 'sem-mobile-898ea',
    authDomain: 'sem-mobile-898ea.firebaseapp.com',
    storageBucket: 'sem-mobile-898ea.firebasestorage.app',
    measurementId: 'G-PVTEXCLVFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8GPdEIJQtT3k8g1Qt4l4XVZeKLnPidw',
    appId: '1:224817571256:android:bfe8a57ba15793313f9b4d',
    messagingSenderId: '224817571256',
    projectId: 'sem-mobile-898ea',
    storageBucket: 'sem-mobile-898ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82kpVYVN2m7qYSW849KYiT1Txwu2SfPs',
    appId: '1:224817571256:ios:f824bad00cea91453f9b4d',
    messagingSenderId: '224817571256',
    projectId: 'sem-mobile-898ea',
    storageBucket: 'sem-mobile-898ea.firebasestorage.app',
    iosBundleId: 'com.example.semMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82kpVYVN2m7qYSW849KYiT1Txwu2SfPs',
    appId: '1:224817571256:ios:f824bad00cea91453f9b4d',
    messagingSenderId: '224817571256',
    projectId: 'sem-mobile-898ea',
    storageBucket: 'sem-mobile-898ea.firebasestorage.app',
    iosBundleId: 'com.example.semMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEE4DgsAAal4GqxFaxUNCtibUEBhxVvWA',
    appId: '1:224817571256:web:be70d16e73b68d883f9b4d',
    messagingSenderId: '224817571256',
    projectId: 'sem-mobile-898ea',
    authDomain: 'sem-mobile-898ea.firebaseapp.com',
    storageBucket: 'sem-mobile-898ea.firebasestorage.app',
    measurementId: 'G-00WG2QC0Q5',
  );
}
